import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const [apiData,setapiData] = useState([]);

  useEffect(() => {
      axios.get('https://dragonsguto.herokuapp.com/dragons/find')
      .then((getData) => {
          setapiData(getData.data) //bota aqui o setapiData dps (e dpos getData.data) (antes tava o consolog.() para estudar)
      })
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.grid}>
            <form action="/send-data-here" method="post">
              <label for="first">name:</label>
              <input type="text" id="first" name="first" />
              <label for="last">Last name:</label>
              <input type="text" id="last" name="last" />
              <button type="submit">Submit</button>
            </form>
        </div>

        <div>
          <table>
              <tbody>
                  <tr>
                      <th>id</th>
                      <th>Nome</th>
                      <th>Sobrenome</th>
                  </tr>
                  {apiData.map(i => (
                      <tr key={i.id}> {/* key props para cada elemento*/}
                          <th>{i.id}</th>
                          <th>{i.name}</th>
                          <th>{i.type}</th>
                      </tr>
                  ))} 
              </tbody>
          </table>
        </div>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
